/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unab.edu.Vista;

import com.unab.edu.DAO.ClsEstudiante;
import com.unab.edu.DAO.ClsPersona;

import com.unab.edu.Entidades.Estudiante;
import com.unab.edu.Entidades.Persona;
import java.util.ArrayList;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Stanly
 */
public class CrudEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form CrudEstudiante
     */
    public CrudEstudiante() {
        initComponents();
        MostrarTablaEstudiante();
        MostrarTablaSeleccionPersona();
      
    }

    void MostrarTablaEstudiante() {

        String TITULOS[] = {"IDESTUDIANTE", "MATRICULA", "IDPERSONA", "NOMBRE ", "USUARIO", "PASSWORD", "NIE"};
        DefaultTableModel Modelotb = new DefaultTableModel(null, TITULOS);
        ClsEstudiante ClaseEstuiante = new ClsEstudiante();
        var estudi = ClaseEstuiante.MostrarEstudiante();
        String filas[] = new String[7];
        for (var iterardatosEstudiante : estudi) {
            filas[0] = String.valueOf(iterardatosEstudiante.getId());
            filas[1] = String.valueOf(iterardatosEstudiante.getMatricula());
            filas[2] = String.valueOf(iterardatosEstudiante.getIdPersona());
            filas[3] = iterardatosEstudiante.getNombre();
            filas[4] = iterardatosEstudiante.getUsu();
            filas[5] = iterardatosEstudiante.getPass();
            filas[6] = iterardatosEstudiante.getNIE();
            Modelotb.addRow(filas);

        }
        tb_mostrarestudiante.setModel(Modelotb);

    }

    void MostrarTablaSeleccionPersona() {

        String TITULOS[] = {"ID", "NOMBRE"};
        DefaultTableModel ModeloTabla = new DefaultTableModel(null, TITULOS);
        ClsPersona ClasePersona = new ClsPersona();
        ArrayList<Persona> Personas = ClasePersona.MostrarPersona();
        String filas[] = new String[2];
        for (var IterarDatosPersona : Personas) {
            filas[0] = String.valueOf(IterarDatosPersona.getIdPersona());
            filas[1] = IterarDatosPersona.getNombre();
           ModeloTabla.addRow(filas);
        }
        Tb_mostrarselecionpersona.setModel(ModeloTabla);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtIDEstuiante = new javax.swing.JTextField();
        txtmatricula = new javax.swing.JTextField();
        txtIDpersona = new javax.swing.JTextField();
        txtUSUARIO = new javax.swing.JTextField();
        txtPassword = new javax.swing.JTextField();
        txtNie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tb_mostrarselecionpersona = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_mostrarestudiante = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Fax", 2, 10)); // NOI18N
        jLabel1.setText("ID Estudiante");

        jLabel2.setFont(new java.awt.Font("Lucida Fax", 2, 10)); // NOI18N
        jLabel2.setText("Matricula");

        jlabel3.setFont(new java.awt.Font("Lucida Fax", 2, 10)); // NOI18N
        jlabel3.setText("IdPersona");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 0, 10)); // NOI18N
        jLabel4.setText("Usuario");

        jLabel5.setFont(new java.awt.Font("Lucida Fax", 2, 10)); // NOI18N
        jLabel5.setText("Password");

        jLabel6.setFont(new java.awt.Font("Lucida Fax", 2, 10)); // NOI18N
        jLabel6.setText("Nie");

        jButton1.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Monospaced", 2, 12)); // NOI18N
        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        Tb_mostrarselecionpersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        Tb_mostrarselecionpersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tb_mostrarselecionpersonaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Tb_mostrarselecionpersona);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNie, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jlabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(txtIDEstuiante, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addGap(102, 102, 102)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(125, 125, 125))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIDEstuiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIDpersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Operaciones de insercion de datos", jPanel1);

        tb_mostrarestudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_mostrarestudiante.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_mostrarestudianteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_mostrarestudiante);

        jTabbedPane2.addTab("", jScrollPane1);

        jTabbedPane1.addTab("Mostrar datos", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        ClsEstudiante estu = new ClsEstudiante();
        Estudiante es = new Estudiante();
        //es.setId(Integer.parseInt(txtIDEstuiante.getText()));
        es.setMatricula(Integer.parseInt(txtmatricula.getText()));
        es.setIdPersona(Integer.parseInt(txtIDpersona.getText()));
        es.setUsu(txtUSUARIO.getText());
        es.setPass(txtPassword.getText());
        es.setNIE(txtNie.getText());

        estu.GuardarEstudiante(es);
        MostrarTablaEstudiante();


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        ClsEstudiante estu = new ClsEstudiante();
        Estudiante es = new Estudiante();
        es.setId(Integer.parseInt(txtIDEstuiante.getText()));
        estu.BorrarEstudiante(es);
        MostrarTablaEstudiante();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//
        ClsEstudiante estu = new ClsEstudiante();
        Estudiante es = new Estudiante();
        es.setId(Integer.parseInt(txtIDEstuiante.getText()));
        es.setMatricula(Integer.parseInt(txtmatricula.getText()));
        es.setIdPersona(Integer.parseInt(txtIDpersona.getText()));
        es.setUsu(txtUSUARIO.getText());
        es.setPass(txtPassword.getText());
        es.setNIE(txtNie.getText());

        estu.ActualizarEstuiante(es);
        MostrarTablaEstudiante();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tb_mostrarestudianteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_mostrarestudianteMouseClicked


        jTabbedPane1.setSelectedIndex(jTabbedPane1.indexOfComponent(jPanel1));
        int fila = tb_mostrarestudiante.getSelectedRow();

        String ID = String.valueOf(tb_mostrarestudiante.getValueAt(fila, 0));
        String matricula = String.valueOf(tb_mostrarestudiante.getValueAt(fila, 1));
        String Idpersona = String.valueOf(tb_mostrarestudiante.getValueAt(fila, 2));
        String usuario = String.valueOf(tb_mostrarestudiante.getValueAt(fila, 3));
        String pass = String.valueOf(tb_mostrarestudiante.getValueAt(fila, 4));
        String nie = String.valueOf(tb_mostrarestudiante.getValueAt(fila, 5));
        
        txtIDEstuiante.setText(ID);
        txtmatricula.setText(matricula);
        txtIDpersona.setText(Idpersona);
        txtUSUARIO.setText(usuario);
        txtPassword.setText(pass);
        txtNie.setText(nie);


    }//GEN-LAST:event_tb_mostrarestudianteMouseClicked

    private void Tb_mostrarselecionpersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tb_mostrarselecionpersonaMouseClicked
       
        int fila = Tb_mostrarselecionpersona.getSelectedRow();
        String Id =  String.valueOf(Tb_mostrarselecionpersona.getValueAt(fila, 0));
        txtIDpersona.setText(Id);
    }//GEN-LAST:event_Tb_mostrarselecionpersonaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudEstudiante().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tb_mostrarselecionpersona;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel jlabel3;
    private javax.swing.JTable tb_mostrarestudiante;
    private javax.swing.JTextField txtIDEstuiante;
    private javax.swing.JTextField txtIDpersona;
    private javax.swing.JTextField txtNie;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUSUARIO;
    private javax.swing.JTextField txtmatricula;
    // End of variables declaration//GEN-END:variables
}
